---
deployment:
  tasks:
    - export DEPLOYPATH=/home/uninetke/public_html
    - /bin/mkdir -p $DEPLOYPATH/wp-content/plugins/uninet-core
    - /bin/mkdir -p $DEPLOYPATH/wp-content/themes/uninet-child
    - /bin/cp -R wp-content/plugins/uninet-core/. $DEPLOYPATH/wp-content/plugins/uninet-core/
    - /bin/cp -R wp-content/themes/uninet-child/. $DEPLOYPATH/wp-content/themes/uninet-child/
